import { VehicleListing } from './luxuryTypes';

export const PREMIUM_SEED_VEHICLES: VehicleListing[] = [
  {
    id: 'luxe-bugatti-chiron',
    title: 'Bugatti Chiron Super Sport 300+ Limited Edition',
    brand: 'Bugatti',
    modelYear: '2024',
    priceFormatted: 'PKR 125.0 Crore',
    priceRaw: 1250000000,
    mileage: '150 KM',
    mileageRaw: 150,
    fuelType: 'Essence',
    images: [
      'https://images.unsplash.com/photo-1600706432502-75a0e2b344e5?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&q=80&w=600'
    ],
    isPremium: true,
    category: 'Hypercar',
    engineCC: 7993,
    horsepower: 1578,
    exteriorColor: 'Black Carbon & Jet Orange',
    conditionScore: 10.0,
    transmission: 'Automatic',
    description: 'The absolute pinnacle of automotive engineering. 1 of only 30 units produced globally. Complete carbon fibre weave matching, limited-production telemetry tracking, fully duty paid clearance, available under specialized bank escrow.',
    isSold: false,
    isReserved: true,
  },
  {
    id: 'luxe-porsche-gt3rs',
    title: 'Porsche 911 GT3 RS Weissach Package (Type 992)',
    brand: 'Porsche',
    modelYear: '2024',
    priceFormatted: 'PKR 16.8 Crore',
    priceRaw: 168000000,
    mileage: '650 KM',
    mileageRaw: 650,
    fuelType: 'Essence',
    images: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&q=80&w=600'
    ],
    isPremium: true,
    category: 'Supercar',
    engineCC: 3996,
    horsepower: 518,
    exteriorColor: 'GT Silver Metallic',
    conditionScore: 9.9,
    transmission: 'Automatic',
    description: 'Fitted with the ultra-desirable Weissach weight-reduction package. Fully dynamic active rear wing, carbon-weave anti-roll bars, magnesium wheels, and zero road stone chips. Complete dealer service logs from Porsche Center.',
    isSold: false,
    isReserved: false,
  },
  {
    id: 'luxe-ferrari-sf90',
    title: 'Ferrari SF90 Stradale Assetto Fiorano Hybrid',
    brand: 'Ferrari',
    modelYear: '2023',
    priceFormatted: 'PKR 22.5 Crore',
    priceRaw: 225000000,
    mileage: '1,200 KM',
    mileageRaw: 1200,
    fuelType: 'Hybrid',
    images: [
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1592853625601-bb9d23111f0c?auto=format&fit=crop&q=80&w=600'
    ],
    isPremium: true,
    category: 'Hypercar',
    engineCC: 3990,
    horsepower: 986,
    exteriorColor: 'Rosso Corsa Red',
    conditionScore: 9.8,
    transmission: 'Automatic',
    description: 'The first ever hybrid plug-in supercar from Maranello. Assetto Fiorano specification with carbon fiber door panels, titanium exhaust system, and upgraded Michelin Pilot Sport Cup 2 tyres. Breathtaking torque-vectoring AWD.',
    isSold: false,
    isReserved: false,
  },
  {
    id: 'luxe-range-rover',
    title: 'Range Rover Autobiography LWB SV Signature',
    brand: 'Land Rover',
    modelYear: '2023',
    priceFormatted: 'PKR 11.5 Crore',
    priceRaw: 115000000,
    mileage: '4,500 KM',
    mileageRaw: 4500,
    fuelType: 'Diesel',
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1608508060064-984bb3526685?auto=format&fit=crop&q=80&w=600'
    ],
    isPremium: true,
    category: 'Luxury SUV',
    engineCC: 2997,
    horsepower: 346,
    exteriorColor: 'Belgravia Green Metallic',
    conditionScore: 9.7,
    transmission: 'Automatic',
    description: 'The ultimate executive utility vehicle. Long wheelbase configuration with dual-screen rear theater systems, individual massage reclining seats, central high-luxury champagne chiller box, and executive flight tray tables.',
    isSold: false,
    isReserved: false,
  },
  {
    id: 'luxe-rolls-spectre',
    title: 'Rolls-Royce Spectre Black Badge Dual-Motor EV',
    brand: 'Rolls-Royce',
    modelYear: '2024',
    priceFormatted: 'PKR 28.5 Crore',
    priceRaw: 285000000,
    mileage: '320 KM',
    mileageRaw: 320,
    fuelType: 'Electric',
    images: [
      'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=600'
    ],
    isPremium: true,
    category: 'Luxury SUV',
    engineCC: 0,
    horsepower: 584,
    exteriorColor: 'Tempest Grey & Mandarin',
    conditionScore: 9.9,
    transmission: 'Automatic',
    description: 'The world\'s premier electric super-coupe luxury grand tourer. Black Badge performance tuning, 23-inch bespoke polished sport wheels, signature starlight headliner spanning door-to-door, absolute quiet luxury acoustic acoustics.',
    isSold: false,
    isReserved: false,
  },
  {
    id: 'luxe-shelby-gt500',
    title: 'Ford Mustang Shelby GT500 Eleanor Classic V8',
    brand: 'Ford',
    modelYear: '1967',
    priceFormatted: 'PKR 5.2 Crore',
    priceRaw: 52000000,
    mileage: '12,000 KM',
    mileageRaw: 12000,
    fuelType: 'Essence',
    images: [
      'https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=600'
    ],
    isPremium: false,
    category: 'Classic',
    engineCC: 7010,
    horsepower: 450,
    exteriorColor: 'Pepper Grey Paint with Black Stripes',
    conditionScore: 9.5,
    transmission: 'Manual',
    description: 'Masterfully built tribute restoration of the iconic Eleanor Mustang. Powered by a 427 Shelby FE Big-block engine paired with a classic 5-speed Tremec manual transmission. Active valved headers for a thunderous authentic exhaust tone.',
    isSold: true,
    isReserved: false,
  },
  {
    id: 'luxe-aston-db12',
    title: 'Aston Martin DB12 Super Tourer Launch Edition',
    brand: 'Aston Martin',
    modelYear: '2024',
    priceFormatted: 'PKR 14.2 Crore',
    priceRaw: 142000000,
    mileage: '800 KM',
    mileageRaw: 800,
    fuelType: 'Essence',
    images: [
      'https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&q=80&w=600'
    ],
    isPremium: false,
    category: 'Supercar',
    engineCC: 3982,
    horsepower: 671,
    exteriorColor: 'Iridescent Aston Martin Racing Green',
    conditionScore: 9.8,
    transmission: 'Automatic',
    description: 'Defines the super tourer category. Handcrafted 4.0L Twin-Turbo V8 engine capable of a 202 mph top velocity. Customized hand-stitched tan semi-aniline bridge-of-weir leather dashboard, integrated Bowers & Wilkins surround acoustics.',
    isSold: false,
    isReserved: false,
  },
  {
    id: 'luxe-mercedes-g63',
    title: 'Mercedes-AMG G63 Grand Edition V8 Biturbo',
    brand: 'Mercedes-Benz',
    modelYear: '2023',
    priceFormatted: 'PKR 11.9 Crore',
    priceRaw: 119000000,
    mileage: '3,100 KM',
    mileageRaw: 3100,
    fuelType: 'Essence',
    images: [
      'https://images.unsplash.com/photo-1525609004556-c46c7d6cf0a3?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1617788138017-817ab5744422?auto=format&fit=crop&q=80&w=600'
    ],
    isPremium: true,
    category: 'Luxury SUV',
    engineCC: 3982,
    horsepower: 577,
    exteriorColor: 'Kalahari Gold & Night Black Magno',
    conditionScore: 9.8,
    transmission: 'Automatic',
    description: 'Highly exclusive Grand Edition—limited to 1,000 units globally. Striking gold graphic graphics, gold AMG custom forged wheels, dynamic premium carbon-weave driving wheel trim and exhaust bypass valving mechanics.',
    isSold: false,
    isReserved: false,
  }
];
